export const START_SERVICE_REQUEST = 'START_SERVICE_REQUEST';
export const START_SERVICE_SUCCESS = 'START_SERVICE_SUCCESS';
export const START_SERVICE_FAILURE = 'START_SERVICE_FAILURE';

export const STOP_SERVICE_REQUEST = 'STOP_SERVICE_REQUEST';
export const STOP_SERVICE_SUCCESS = 'STOP_SERVICE_SUCCESS';
export const STOP_SERVICE_FAILURE = 'STOP_SERVICE_FAILURE';